package com.hong.forapw.domain.region.constant;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum District {

    GANGNAM("강남구"),
    GANGDONG("강동구"),
    GANGBUK("강북구"),
    GANGSEO("강서구"),
    GWANAK("관악구"),
    GWANGJIN("광진구"),
    GURO("구로구"),
    GEUMCHEON("금천구"),
    NOWON("노원구"),
    DOBONG("도봉구"),
    DONGDAEMUN("동대문구"),
    DONGJAK("동작구"),
    MAPO("마포구"),
    SEODAEMUN("서대문구"),
    SEOCHO("서초구"),
    SEONGDONG("성동구"),
    SEONGBUK("성북구"),
    SONGPA("송파구"),
    YANGCHEON("양천구"),
    YEONGDEUNGPO("영등포구"),
    YONGSAN("용산구"),
    EUNPYEONG("은평구"),
    JONGNO("종로구"),
    JUNG("중구"),
    JUNGNANG("중랑구"),
    GEUMJEONG("금정구"),
    GIJANG("기장군"),
    NAM("남구"),
    DONG("동구"),
    DONGRAE("동래구"),
    BUSANJIN("부산진구"),
    BUK("북구"),
    SASANG("사상구"),
    SAHA("사하구"),
    SEO("서구"),
    SUYEONG("수영구"),
    YEONJE("연제구"),
    YEONGDO("영도구"),
    HAEUNDAE("해운대구"),
    GUNWI("군위군"),
    DALSEO("달서구"),
    DALSEONG("달성군"),
    SUSEONG("수성구"),
    GANGHWA("강화군"),
    GYEYANG("계양구"),
    NAMDONG("남동구"),
    MICHUHOL("미추홀구"),
    BUPYEONG("부평구"),
    YEONSU("연수구"),
    ONGJIN("옹진군"),
    GWANGSAN("광산구"),
    DAEDEOK("대덕구"),
    YUSEONG("유성구"),
    ULJU("울주군"),
    GAPYEONG("가평군"),
    GOYANG("고양시"),
    GOYANG_DEOKYANG("고양시 덕양구"),
    GOYANG_ILSANDONG("고양시 일산동구"),
    GOYANG_ILSANSO("고양시 일산서구"),
    GWACHEON("과천시"),
    GWANGMYEONG("광명시"),
    GWANGJU("광주시"),
    GURI("구리시"),
    GUNPO("군포시"),
    GIHEUNG("기흥구"),
    GIMPO("김포시"),
    NAMYANGJU("남양주시"),
    DONGDUCHEON("동두천시"),
    BUCHEON("부천시"),
    SEONGNAM("성남시"),
    SEONGNAM_BUNDANG("성남시 분당구"),
    SEONGNAM_SUJEONG("성남시 수정구"),
    SEONGNAM_JUNGWON("성남시 중원구"),
    SUWON("수원시"),
    SUWON_GWONSEON("수원시 권선구"),
    SUWON_YEONGTONG("수원시 영통구"),
    SUWON_JANGAN("수원시 장안구"),
    SUWON_PALDAL("수원시 팔달구"),
    SIHEUNG("시흥시"),
    ANSAN("안산시"),
    ANSAN_DANWON("안산시 단원구"),
    ANSAN_SANGROK("안산시 상록구"),
    ANSEONG("안성시"),
    ANYANG("안양시"),
    ANYANG_DONGAN("안양시 동안구"),
    ANYANG_MANAN("안양시 만안구"),
    YANGJU("양주시"),
    YANGPYEONG("양평군"),
    YEOJU("여주시"),
    YEONCHEON("연천군"),
    OSAN("오산시"),
    YONGIN("용인시"),
    YONGIN_GIHEUNG("용인시 기흥구"),
    YONGIN_SUJI("용인시 수지구"),
    YONGIN_CHEOIN("용인시 처인구"),
    UIWANG("의왕시"),
    UIJEONGBU("의정부시"),
    ICHEON("이천시"),
    PAJU("파주시"),
    PYEONGTAEK("평택시"),
    POCHON("포천시"),
    HANAM("하남시"),
    HWASEONG("화성시"),
    GANGNEUNG("강릉시"),
    GOSEONG_GANGWON("고성군"),
    DONGHAE("동해시"),
    SAMCHEOK("삼척시"),
    SOKCHO("속초시"),
    YANGGU("양구군"),
    YANGYANG("양양군"),
    YEONGWOL("영월군"),
    WONJU("원주시"),
    INJE("인제군"),
    JEONGSEON("정선군"),
    CHEORWON("철원군"),
    CHUNCHEON("춘천시"),
    TAEBAEK("태백시"),
    PYEONGCHANG("평창군"),
    HONGCHEON("홍천군"),
    HWACHEON("화천군"),
    HOENGSEONG("횡성군"),
    GOESAN("괴산군"),
    DANYANG("단양군"),
    BOEUN("보은군"),
    YEONGDONG("영동군"),
    OKCHEON("옥천군"),
    EUMSEONG("음성군"),
    JECCHEON("제천시"),
    JEUNGPYEONG("증평군"),
    JINCHEON("진천군"),
    CHEONGJU("청주시"),
    CHEONGJU_SANGDANG("청주시 상당구"),
    CHEONGJU_SEOWON("청주시 서원구"),
    CHEONGJU_CHEONGWON("청주시 청원구"),
    CHEONGJU_HEUNGDEOK("청주시 흥덕구"),
    CHUNGJU("충주시"),
    GYERYONG("계룡시"),
    GONGJU("공주시"),
    GEUMSAN("금산군"),
    NONSAN("논산시"),
    DANGJIN("당진시"),
    BORYEONG("보령시"),
    BUYEO("부여군"),
    SEOSAN("서산시"),
    SEOCHON("서천군"),
    ASAN("아산시"),
    YEONGI("연기군"),
    YESAN("예산군"),
    CHEONAN("천안시"),
    CHEONAN_DONGNAM("천안시 동남구"),
    CHEONAN_SEOBUK("천안시 서북구"),
    CHEONGYANG("청양군"),
    TAAN("태안군"),
    HONGSEONG("홍성군"),
    GYEONGSAN("경산시"),
    GYEONGJU("경주시"),
    GORYEONG("고령군"),
    GUMI("구미시"),
    GIMCHEON("김천시"),
    MUNGYEONG("문경시"),
    BONGHWA("봉화군"),
    SANGJU("상주시"),
    SEONGJU("성주군"),
    ANDONG("안동시"),
    YEONGDEOK("영덕군"),
    YEONGYANG("영양군"),
    YEONGJU("영주시"),
    YEONGCHEON("영천시"),
    YECHON("예천군"),
    ULLUNG("울릉군"),
    ULJIN("울진군"),
    UISEONG("의성군"),
    CHEONGDO("청도군"),
    CHEONGSONG("청송군"),
    CHILGOK("칠곡군"),
    POHANG("포항시"),
    POHANG_NAM("포항시 남구"),
    POHANG_BUK("포항시 북구"),
    GEOJE("거제시"),
    GEORGEUM("거창군"),
    GOSEONG_GYEONGSANG("고성군"),
    GIMHAE("김해시"),
    NAMHAE("남해군"),
    MIRYANG("밀양시"),
    SACHEON("사천시"),
    SANCHEONG("산청군"),
    YANGSAN("양산시"),
    UIRYEONG("의령군"),
    JINJU("진주시"),
    CHANGNYEONG("창녕군"),
    CHANGWON("창원시"),
    CHANGWON_MASANHAPPO("창원시 마산합포구"),
    CHANGWON_MASANHOEWON("창원시 마산회원구"),
    CHANGWON_SEONGSAN("창원시 성산구"),
    CHANGWON_UICHANG("창원시 의창구"),
    CHANGWON_JINHAE("창원시 진해구"),
    TONGYEONG("통영시"),
    HADONG("하동군"),
    HAMAN("함안군"),
    HAMYANG("함양군"),
    HAPCHEON("합천군"),
    GOCHANG("고창군"),
    GUNSAN("군산시"),
    GIMJE("김제시"),
    NAMWON("남원시"),
    MUJU("무주군"),
    BUAN("부안군"),
    SOONCHANG("순창군"),
    WANJU("완주군"),
    IKSAN("익산시"),
    IMSIL("임실군"),
    JANGSU("장수군"),
    JEONJU("전주시"),
    JEONJU_DEOKJIN("전주시 덕진구"),
    JEONJU_WANSAN("전주시 완산구"),
    JEONGEUP("정읍시"),
    JINAN("진안군"),
    GANGJIN("강진군"),
    GOHEUNG("고흥군"),
    GOKSEONG("곡성군"),
    GWANGYANG("광양시"),
    GURYE("구례군"),
    NAJU("나주시"),
    DAMYANG("담양군"),
    MOKPO("목포시"),
    MUAN("무안군"),
    BOSEONG("보성군"),
    SUNCHEON("순천시"),
    SINAN("신안군"),
    YEOSU("여수시"),
    YEONGGWANG("영광군"),
    YEONGAM("영암군"),
    WANDO("완도군"),
    JANGSEONG("장성군"),
    JANGHEUNG("장흥군"),
    JINDO("진도군"),
    HAMPEONG("함평군"),
    HAENAM("해남군"),
    HWASUN("화순군"),
    JEJU("제주시"),
    SEOGWIPO("서귀포시");

    private final String value;
}